version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:1.30.1
    
    steps:
      - checkout
      - run:
          name: test3
          command: |
            source ~/.cargo/env
            export PATH=~/.cargo/bin:$PATH
            cargo test test3 -- --nocapture

