version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    
    steps:
      - checkout
      - run:
          name: preparation
          command: |
            apt-get update
            apt-get install -y curl wget
            wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
            chmod +x rustup-init
            ./rustup-init -y --no-modify-path --default-toolchain nightly
            RUSTUP=~/.cargo/bin/rustup
            CARGO=~/.cargo/bin/cargo
            chmod -R a+w $RUSTUP $CARGO
            rm rustup-init
            source ~/.cargo/env
      - run:
          name: test3
          command: |
            cargo test test3 -- --nocapture

