version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:1.30.1
    
    steps:
      - checkout
      - run:
          name: dijkstra_test
          command: |
            cargo test dijkstra_test -- --nocapture

